/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fatec.poo.view;

import fatec.poo.model.Cliente;
import fatec.poo.model.ItemPedido;
import fatec.poo.model.Pedido;
import fatec.poo.model.Pessoa;
import fatec.poo.model.Produto;
import fatec.poo.model.Vendedor;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author mathe
 */
public class GuiEmitirPedido extends javax.swing.JFrame {

    /**
     * Creates new form GuiEmitirPedido
     */
    public GuiEmitirPedido(ArrayList<Pedido> ped, ArrayList<Produto> prod, ArrayList<Pessoa> pes) {
        initComponents();
        pedido = ped;
        produto = prod;
        clie_vend = pes;
        modTbProduto= (DefaultTableModel)tbProduto.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngrFormaPagamento = new javax.swing.ButtonGroup();
        jPanelPedido = new javax.swing.JPanel();
        lblNumPed = new javax.swing.JLabel();
        txtNumPed = new javax.swing.JTextField();
        btnConsultarPedido = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jPanelFormaPag = new javax.swing.JPanel();
        rbtnVista = new javax.swing.JRadioButton();
        rbtnPrazo = new javax.swing.JRadioButton();
        btnValidar = new javax.swing.JButton();
        ftxtDataPedido = new javax.swing.JFormattedTextField();
        jPanelDadosCliente = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ftxtCPFCliente = new javax.swing.JFormattedTextField();
        btnConsultarCliente = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        jPanelItensPedido = new javax.swing.JPanel();
        btnConsultarItemPedido = new javax.swing.JButton();
        lblItemPedido = new javax.swing.JLabel();
        txtcodProd = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtQtd = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblValorTotaltPed = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnAddItem = new javax.swing.JButton();
        btnRemoveItem = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbProduto = new javax.swing.JTable();
        lblQtdeItensPedido = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jPanelDadosVendedor = new javax.swing.JPanel();
        ftxtCPFVendedor = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        btnConsultarVendedor = new javax.swing.JButton();
        lblVendedor = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        brnAlterar = new javax.swing.JButton();
        btnIncluir = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Emitir Pedido");

        jPanelPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Pedido"));

        lblNumPed.setText("Número do Pedido");

        btnConsultarPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultarPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnConsultarPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarPedidoActionPerformed(evt);
            }
        });

        jLabel3.setText("Data do Pedido");

        jPanelFormaPag.setBorder(javax.swing.BorderFactory.createTitledBorder("Forma de Pagamento"));

        btngrFormaPagamento.add(rbtnVista);
        rbtnVista.setSelected(true);
        rbtnVista.setText("A Vista");
        rbtnVista.setEnabled(false);

        btngrFormaPagamento.add(rbtnPrazo);
        rbtnPrazo.setText("A Prazo");
        rbtnPrazo.setEnabled(false);

        javax.swing.GroupLayout jPanelFormaPagLayout = new javax.swing.GroupLayout(jPanelFormaPag);
        jPanelFormaPag.setLayout(jPanelFormaPagLayout);
        jPanelFormaPagLayout.setHorizontalGroup(
            jPanelFormaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormaPagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbtnVista)
                .addGap(18, 18, 18)
                .addComponent(rbtnPrazo))
        );
        jPanelFormaPagLayout.setVerticalGroup(
            jPanelFormaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelFormaPagLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelFormaPagLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnVista)
                    .addComponent(rbtnPrazo)))
        );

        btnValidar.setText("Validar");
        btnValidar.setEnabled(false);
        btnValidar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnValidarActionPerformed(evt);
            }
        });

        try {
            ftxtDataPedido.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDataPedido.setEnabled(false);

        javax.swing.GroupLayout jPanelPedidoLayout = new javax.swing.GroupLayout(jPanelPedido);
        jPanelPedido.setLayout(jPanelPedidoLayout);
        jPanelPedidoLayout.setHorizontalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblNumPed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNumPed, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarPedido)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ftxtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btnValidar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanelFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
        );
        jPanelPedidoLayout.setVerticalGroup(
            jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPedidoLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanelPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumPed)
                    .addComponent(txtNumPed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultarPedido)
                    .addComponent(jLabel3)
                    .addComponent(btnValidar)
                    .addComponent(ftxtDataPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPedidoLayout.createSequentialGroup()
                .addComponent(jPanelFormaPag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanelDadosCliente.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Cliente"));

        jLabel1.setText("CPF Cliente");

        try {
            ftxtCPFCliente.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCPFCliente.setEnabled(false);

        btnConsultarCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultarCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnConsultarCliente.setEnabled(false);
        btnConsultarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarClienteActionPerformed(evt);
            }
        });

        lblCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanelDadosClienteLayout = new javax.swing.GroupLayout(jPanelDadosCliente);
        jPanelDadosCliente.setLayout(jPanelDadosClienteLayout);
        jPanelDadosClienteLayout.setHorizontalGroup(
            jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(ftxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarCliente)
                .addGap(18, 18, 18)
                .addComponent(lblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelDadosClienteLayout.setVerticalGroup(
            jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDadosClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(ftxtCPFCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnConsultarCliente)))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanelItensPedido.setBorder(javax.swing.BorderFactory.createTitledBorder("Itens do Pedido"));

        btnConsultarItemPedido.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultarItemPedido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnConsultarItemPedido.setEnabled(false);
        btnConsultarItemPedido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarItemPedidoActionPerformed(evt);
            }
        });

        lblItemPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblItemPedido.setEnabled(false);

        txtcodProd.setEnabled(false);

        jLabel6.setText("Código do Produto");

        txtQtd.setEnabled(false);

        jLabel7.setText("Qtde Vendida");

        lblValorTotaltPed.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblValorTotaltPed.setEnabled(false);

        jLabel4.setText("Valor total do pedido");

        jLabel5.setText("Quantidade de itens pedido");

        btnAddItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnAddItem.setText("Adicionar item");
        btnAddItem.setEnabled(false);
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        btnRemoveItem.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnRemoveItem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/rem.png"))); // NOI18N
        btnRemoveItem.setText("Remover Itens");
        btnRemoveItem.setEnabled(false);
        btnRemoveItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveItemActionPerformed(evt);
            }
        });

        tbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Preco. Unit", "Qutd. Vend", "SubTotal"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbProduto);

        lblQtdeItensPedido.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        lblQtdeItensPedido.setEnabled(false);

        javax.swing.GroupLayout jPanelItensPedidoLayout = new javax.swing.GroupLayout(jPanelItensPedido);
        jPanelItensPedido.setLayout(jPanelItensPedidoLayout);
        jPanelItensPedidoLayout.setHorizontalGroup(
            jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItensPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItensPedidoLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtcodProd, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnConsultarItemPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblItemPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(jPanelItensPedidoLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAddItem)
                        .addGap(69, 69, 69)
                        .addComponent(btnRemoveItem)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItensPedidoLayout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItensPedidoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQtdeItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblValorTotaltPed, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43))
        );
        jPanelItensPedidoLayout.setVerticalGroup(
            jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelItensPedidoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelItensPedidoLayout.createSequentialGroup()
                        .addComponent(btnConsultarItemPedido)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelItensPedidoLayout.createSequentialGroup()
                        .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(txtcodProd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(txtQtd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblItemPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAddItem)
                            .addComponent(btnRemoveItem))
                        .addGap(27, 27, 27)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(lblValorTotaltPed, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelItensPedidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblQtdeItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        btnSair.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/exit.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanelDadosVendedor.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados Vendedor"));

        try {
            ftxtCPFVendedor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtCPFVendedor.setEnabled(false);

        jLabel2.setText("CPF Vendedor");

        btnConsultarVendedor.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnConsultarVendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/pesq.png"))); // NOI18N
        btnConsultarVendedor.setEnabled(false);
        btnConsultarVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarVendedorActionPerformed(evt);
            }
        });

        lblVendedor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout jPanelDadosVendedorLayout = new javax.swing.GroupLayout(jPanelDadosVendedor);
        jPanelDadosVendedor.setLayout(jPanelDadosVendedorLayout);
        jPanelDadosVendedorLayout.setHorizontalGroup(
            jPanelDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(6, 6, 6)
                .addComponent(ftxtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultarVendedor)
                .addGap(18, 18, 18)
                .addComponent(lblVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelDadosVendedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41))
        );
        jPanelDadosVendedorLayout.setVerticalGroup(
            jPanelDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDadosVendedorLayout.createSequentialGroup()
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanelDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnConsultarVendedor, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanelDadosVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(ftxtCPFVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        brnAlterar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        brnAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Alterar.png"))); // NOI18N
        brnAlterar.setText("Alterar");
        brnAlterar.setEnabled(false);
        brnAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnAlterarActionPerformed(evt);
            }
        });

        btnIncluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/add.png"))); // NOI18N
        btnIncluir.setText("Incluir");
        btnIncluir.setEnabled(false);
        btnIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIncluirActionPerformed(evt);
            }
        });

        btnExcluir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Eraser.png"))); // NOI18N
        btnExcluir.setText("Excluir");
        btnExcluir.setEnabled(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanelPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDadosCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelItensPedido, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanelDadosVendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(218, 218, 218)
                        .addComponent(btnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(brnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDadosCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelDadosVendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelItensPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIncluir)
                    .addComponent(brnAlterar)
                    .addComponent(btnExcluir)
                    .addComponent(btnSair))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
        
        valor = 0;
        int x;

        if ("0".equals(txtQtd.getText())) {
            valor = 0;
        } //else if ( Double.parseDouble(txtQtd.getText())  <=produto.get(posProduto).getEstoqueMinimo()  ){
        else if ((produto.get(posProduto).getQtdeEstoque() - produto.get(posProduto).getEstoqueMinimo()) >= Double.parseDouble(txtQtd.getText())) {
            iped = new ItemPedido(modTbProduto.getRowCount(), Double.parseDouble(txtQtd.getText()), produto.get(posProduto));
            subtotal = produto.get(posProduto).getPreco() * (Integer.parseInt(txtQtd.getText()));
            valor = 1;

           for (x = 0; x < clie_vend.size(); x++) {
                if (clie_vend.get(x) instanceof Cliente) {
                    if (((Cliente) clie_vend.get(x)).getCpf().equals(ftxtCPFCliente.getText())) {
                        break;
                    }
                }
            }
            if (x < clie_vend.size()) {
                posPesClie = x;
            } else {
                posPesClie = -1;
            }
            if (clie_vend.get(posPesClie) instanceof Cliente) {
       
                if (subtotal <= ((Cliente) clie_vend.get(posPesClie)).getLimiteDisp()) {
                    ((Cliente) clie_vend.get(posPesClie)).setLimiteDisp(((Cliente) clie_vend.get(posPesClie)).getLimiteDisp() - subtotal);

                    ped.addItensPedido(iped);
                    
                    DecimalFormat Fr = new DecimalFormat("##.##");

                    String linha[] = {txtcodProd.getText(), produto.get(posProduto).getDescricao(), String.valueOf(produto.get(posProduto).getPreco()), String.valueOf(txtQtd.getText())};

                    modTbProduto.addRow(linha);
                    iped.tirarEstoque();

                    modTbProduto.setValueAt(Fr.format(subtotal), modTbProduto.getRowCount() - 1, 4);

                    total += subtotal;
                   
                   
                    
                    lblQtdeItensPedido.setText(String.valueOf(modTbProduto.getRowCount()));
                    lblValorTotaltPed.setText(String.valueOf(total));
                    codItemPedido++;
                    btnIncluir.setEnabled(true);

                    
                   
                    
                } else {
                    JOptionPane.showMessageDialog(null, "VALOR DA COMPRA SUPERIOR AO LIMITE DISPONÍVEL DO CLIENTE!", "Aviso", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
        if (valor == 0) {
            JOptionPane.showMessageDialog(null, "Quantidade Invalida", "Aviso", JOptionPane.WARNING_MESSAGE);
            txtQtd.setText(null);
            txtQtd.requestFocus();
        }

    }//GEN-LAST:event_btnAddItemActionPerformed

    private void btnConsultarPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarPedidoActionPerformed

        int x;
        double total=0;
        for (x = 0; x < pedido.size(); x++) {
            if (pedido.get(x) instanceof Pedido) {
                if (((Pedido) pedido.get(x)).getNumero().equals(txtNumPed.getText())) {
                    break;
                }
            }
        }

        if (x < pedido.size()) {
            posPedido = x;
        } else {
            posPedido = -1;
        }

        if (posPedido >= 0) {
            txtNumPed.setText((pedido.get(posPedido)).getNumero());
            ftxtDataPedido.setText((pedido.get(posPedido)).getDataEmissao());
            ftxtCPFCliente.setText(pedido.get(posPedido).getCliente().getCpf());
            lblCliente.setText(pedido.get(posPedido).getCliente().getNome());
            ftxtCPFVendedor.setText(pedido.get(posPedido).getVendedor().getCpf());
            lblVendedor.setText(pedido.get(posPedido).getVendedor().getNome());
            
            ///int qtdItem = modTbProduto.getRowCount();
            int qtdItem = pedido.get(posPedido).getItenspedido().size();
            for (x = 0; x < qtdItem; x++) {
                String codProd = pedido.get(posPedido).getItenspedido().get(x).getProduto().getCodigo();
                String descricao = pedido.get(posPedido).getItenspedido().get(x).getProduto().getDescricao();
                String preco = String.valueOf(pedido.get(posPedido).getItenspedido().get(x).getProduto().getPreco());
                String qtdeVend = String.valueOf(pedido.get(posPedido).getItenspedido().get(x).getQtdeVendida());
                String subtotal = String.valueOf(pedido.get(posPedido).getItenspedido().get(x).getQtdeVendida()* pedido.get(posPedido).getItenspedido().get(x).getProduto().getPreco());
                
                total+= Double.parseDouble(subtotal);
                
                String linha[] = {codProd,descricao,preco,qtdeVend,subtotal};
                modTbProduto.addRow(linha);
                
                
            }
           
             if (pedido.get(posPedido).isFormaPagto()== true) {
                rbtnVista.setSelected(true);
                
            }
            if (pedido.get(posPedido).isFormaPagto()== false) {
                rbtnPrazo.setSelected(true);
            }
            
            lblValorTotaltPed.setText(String.valueOf(total));
            lblQtdeItensPedido.setText(String.valueOf(qtdItem));
            brnAlterar.setEnabled(true);
            txtcodProd.setEnabled(true);
            btnAddItem.setEnabled(true);
            btnRemoveItem.setEnabled(true);
            btnConsultarItemPedido.setEnabled(true);
            txtQtd.setEditable(true);
            
            btnExcluir.setEnabled(true);

        } else {
            ped = new Pedido(txtNumPed.getText(), ftxtDataPedido.getText());
            btnConsultarPedido.setEnabled(false);
            ftxtDataPedido.setEnabled(true);
            btnConsultarCliente.setEnabled(true);
            btnValidar.setEnabled(true);
            //btnConsultarVendedor.setEnabled(false);
            rbtnPrazo.setEnabled(true);
            rbtnVista.setEnabled(true);       
        }
            btnConsultarPedido.setEnabled(false);
    }//GEN-LAST:event_btnConsultarPedidoActionPerformed

    private void btnConsultarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarClienteActionPerformed
        int x;
   
        
           
            for (x = 0; x < clie_vend.size(); x++) {
            if (clie_vend.get(x) instanceof Cliente) {
                if (((Cliente) clie_vend.get(x)).getCpf().equals(ftxtCPFCliente.getText())) {
                    cliente = (Cliente) clie_vend.get(x);
                    break;
                }
            }    
        }
        if (x < clie_vend.size()) {
                posPesClie = x;
        }else {
                posPesClie = -1;
        }

        if (posPesClie >= 0) {
            ftxtCPFCliente.setText(((Cliente)clie_vend.get(posPesClie)).getCpf());
            lblCliente.setText(clie_vend.get(posPesClie).getNome());
            ftxtCPFVendedor.setEnabled(true);
            btnConsultarVendedor.setEnabled(true);
            ftxtDataPedido.setEnabled(false);
            btnValidar.setEnabled(false);
            ftxtCPFCliente.setEnabled(false);
            btnConsultarCliente.setEnabled(false);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "CPF INVALIDO OU NÃO CADASTRADO!", "Aviso", JOptionPane.WARNING_MESSAGE);

        }
        
        
    }//GEN-LAST:event_btnConsultarClienteActionPerformed

    private void btnConsultarVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarVendedorActionPerformed
        int x;
        for (x = 0; x < clie_vend.size(); x++) {
            if (clie_vend.get(x) instanceof Vendedor) {
                if (((Vendedor) clie_vend.get(x)).getCpf().equals(ftxtCPFVendedor.getText())) {
                    vendedor = (Vendedor) clie_vend.get(x);
                    break;
                }
            }    
        }
        if (x < clie_vend.size()) {
                posPesClie = x;
        }else {
                posPesClie = -1;
        }

        if (posPesClie >= 0) {
            ftxtCPFVendedor.setText(((Vendedor)clie_vend.get(posPesClie)).getCpf());
            lblVendedor.setText(clie_vend.get(posPesClie).getNome());
            ftxtCPFVendedor.setEnabled(false);
            txtcodProd.setEnabled(true);
            btnConsultarVendedor.setEnabled(false);
            btnConsultarItemPedido.setEnabled(true);
            ftxtCPFCliente.setEnabled(false);
            
            
        }else{
            JOptionPane.showMessageDialog(null, "CPF INVALIDO OU NÃO CADASTRADO!", "Aviso", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_btnConsultarVendedorActionPerformed

    private void btnValidarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnValidarActionPerformed
    
        if(Pedido.ValidarData(ftxtDataPedido.getText()) == false){ 
            JOptionPane.showMessageDialog(null, "DATA INVÁLIDA!", "Aviso", JOptionPane.WARNING_MESSAGE);
            ftxtDataPedido.setText(null);
            ftxtDataPedido.requestFocus();
            
        }else{
        ftxtDataPedido.setEnabled(false);
        btnValidar.setEnabled(false);
        ftxtCPFCliente.setEnabled(true);
        
         }            
        
    }//GEN-LAST:event_btnValidarActionPerformed

    private void btnConsultarItemPedidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarItemPedidoActionPerformed
      int x;
        for (x = 0; x < produto.size(); x++) {
            if (produto.get(x) instanceof Produto) {
                if (((Produto) produto.get(x)).getCodigo().equals(txtcodProd.getText())) {
                    prod = (Produto) produto.get(x);
                    break;
                }
            }    
        }
        if (x < produto.size()) {
                posProduto = x;
        }else {
                posProduto = -1;
        }

        if (posProduto >= 0) {
            txtcodProd.setText(((Produto)produto.get(posProduto)).getCodigo());
            lblItemPedido.setText(produto.get(posProduto).getDescricao());
            btnAddItem.setEnabled(true);
            btnRemoveItem.setEnabled(true);
            txtQtd.setEnabled(true);
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "CODIGO INVALIDO OU NÃO CADASTRADO!", "Aviso", JOptionPane.WARNING_MESSAGE);

        }
        
        
        
    }//GEN-LAST:event_btnConsultarItemPedidoActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
    
       if (posPedido >= 0) {
            pedido.remove(posPedido);
            posPedido = -1;
        }
        txtNumPed.setText(null);
        ftxtDataPedido.setText(null);
        //forma de pagamento
        ftxtCPFCliente.setText(null);
        lblCliente.setText(null);
        ftxtCPFVendedor.setText(null);
        lblVendedor.setText(null);
        txtcodProd.setText(null);
        lblItemPedido.setText(null);
        lblValorTotaltPed.setText(null);
        lblQtdeItensPedido.setText(null);
        txtQtd.setText(null);
        btnConsultarPedido.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarItemPedido.setEnabled(false);
         btnAddItem.setEnabled(false);
        btnRemoveItem.setEnabled(false);
        btnIncluir.setEnabled(false);
        brnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtNumPed.setEnabled(true);
        ftxtDataPedido.setEnabled(false);
        //forma de pagamento
        ftxtCPFCliente.setEnabled(false);
        lblCliente.setEnabled(false);
        ftxtCPFVendedor.setEnabled(false);
        lblVendedor.setEnabled(false);
        txtcodProd.setEnabled(false);
        lblItemPedido.setEnabled(false);
        lblValorTotaltPed.setEnabled(false);
        lblQtdeItensPedido.setEnabled(false);
        txtQtd.setEnabled(false);
         txtNumPed.requestFocus();
         //
       
         modTbProduto.setNumRows(0);
        
        
        
        
        
        
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnRemoveItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveItemActionPerformed
        int x;
        for (x = 0; x < clie_vend.size(); x++) {
            if (clie_vend.get(x) instanceof Cliente) {
                if (((Cliente) clie_vend.get(x)).getCpf().equals(ftxtCPFCliente.getText())) {
                    break;
                }
            }
        }
        if (x < clie_vend.size()) {
            posPesClie = x;
        } else {
            posPesClie = -1;
        }
        if (tbProduto.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(null, "A linha não foi selecionada", "Aviso",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            int i, cont = tbProduto.getRowCount();
            if (clie_vend.get(posPesClie) instanceof Cliente) {
                ((Cliente) clie_vend.get(posPesClie)).setLimiteDisp(((Cliente) clie_vend.get(posPesClie)).getLimiteDisp() + Double.parseDouble((String) tbProduto.getModel().getValueAt(tbProduto.getSelectedRow(), 4)));
            
            }
             
            total -= Double.parseDouble((String) tbProduto.getModel().getValueAt(tbProduto.getSelectedRow(), 4));
            iped.addEstoque(Double.parseDouble((String) tbProduto.getModel().getValueAt(tbProduto.getSelectedRow(), 3)));
            
          
                   
   
            modTbProduto.removeRow(tbProduto.getSelectedRow());
             
            
        }

        lblQtdeItensPedido.setText(String.valueOf(modTbProduto.getRowCount()));
        lblValorTotaltPed.setText(String.valueOf(total));

        //lblValorTotaltPed.setText((String) tbProduto.getModel().getValueAt( tbProduto.getSelectedRow()-1 ,4));

    }//GEN-LAST:event_btnRemoveItemActionPerformed

    private void btnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIncluirActionPerformed

        
        
        if (rbtnVista.isSelected() ) {
            ped.setFormaPagto(true);
            
        }
        if (rbtnPrazo.isSelected()) {
            ped.setFormaPagto(false);
        }
        ped.setDataEmissao(ftxtDataPedido.getText());
        ped.setCliente(cliente);
        ped.setVendedor(vendedor);

        pedido.add(ped);
        
        btnConsultarPedido.setEnabled(true);
        btnIncluir.setEnabled(false);
        brnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        
         txtNumPed.setText(null);
        ftxtDataPedido.setText(null);
        rbtnVista.setSelected(false);
        rbtnPrazo.setSelected(false);
        ftxtCPFCliente.setText(null);
        lblCliente.setText(null);
        ftxtCPFVendedor.setText(null);
        lblVendedor.setText(null);
        txtcodProd.setText(null);
        lblItemPedido.setText(null);
        lblValorTotaltPed.setText(null);
        lblQtdeItensPedido.setText(null);
        txtQtd.setText(null);
        btnConsultarPedido.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarItemPedido.setEnabled(false);
        
         btnAddItem.setEnabled(false);
        btnRemoveItem.setEnabled(false);
        txtNumPed.setEnabled(true);
        ftxtDataPedido.setEnabled(false);
        //forma de pagamento
        ftxtCPFCliente.setEnabled(false);
        lblCliente.setEnabled(false);
        ftxtCPFVendedor.setEnabled(false);
        lblVendedor.setEnabled(false);
        txtcodProd.setEnabled(false);
        lblItemPedido.setEnabled(false);
        lblValorTotaltPed.setEnabled(false);
        lblQtdeItensPedido.setEnabled(false);
        txtQtd.setEnabled(false);
         modTbProduto.setNumRows(0);
        txtNumPed.requestFocus();

        
        //List pedido2 = new ArrayList(pedido);
        

    }//GEN-LAST:event_btnIncluirActionPerformed

    private void brnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnAlterarActionPerformed
        
     
        int x; 
     
        String aux = "";
        ArrayList<ItemPedido> itens = pedido.get(posPedido).getItenspedido();

        for (int i = 0; i < pedido.get(posPedido).getItenspedido().size(); i++) {
            pedido.get(posPedido).getItenspedido().removeAll(itens);
        }

        for (int i = 0; i < modTbProduto.getRowCount(); i++) {
            for (x = 0; x < produto.size(); x++) {
                if (produto.get(x) instanceof Produto) {
                    if (((Produto) produto.get(x)).getCodigo().equals(String.valueOf(modTbProduto.getValueAt(i, 0)))) {
                        break;
                    }
                }
            }
            aux = String.valueOf(modTbProduto.getValueAt(i, 3));
            aux = aux.replace(',', '.');
            ItemPedido item = new ItemPedido(i,
                    Double.parseDouble(aux),
                    produto.get(x));
            ped.addItensPedido(item);
        }

        
  
        txtNumPed.setEnabled(false);

        txtcodProd.setEnabled(true);
        btnConsultarItemPedido.setEnabled(true);
        txtQtd.setEnabled(true);
        btnAddItem.setEnabled(true);
        btnRemoveItem.setEnabled(true);
        
       txtNumPed.setText(null);
        ftxtDataPedido.setText(null);
        //forma de pagamento
        ftxtCPFCliente.setText(null);
        lblCliente.setText(null);
        ftxtCPFVendedor.setText(null);
        lblVendedor.setText(null);
        txtcodProd.setText(null);
        lblItemPedido.setText(null);
        lblValorTotaltPed.setText(null);
        lblQtdeItensPedido.setText(null);
        txtQtd.setText(null);
        btnConsultarPedido.setEnabled(true);
        btnConsultarCliente.setEnabled(false);
        btnConsultarVendedor.setEnabled(false);
        btnConsultarItemPedido.setEnabled(false);
         btnAddItem.setEnabled(false);
        btnRemoveItem.setEnabled(false);
        btnIncluir.setEnabled(false);
        brnAlterar.setEnabled(false);
        btnExcluir.setEnabled(false);
        txtNumPed.setEnabled(true);
        ftxtDataPedido.setEnabled(false);
        //forma de pagamento
        ftxtCPFCliente.setEnabled(false);
        lblCliente.setEnabled(false);
        ftxtCPFVendedor.setEnabled(false);
        lblVendedor.setEnabled(false);
        txtcodProd.setEnabled(false);
        lblItemPedido.setEnabled(false);
        lblValorTotaltPed.setEnabled(false);
        lblQtdeItensPedido.setEnabled(false);
        txtQtd.setEnabled(false);
         txtNumPed.requestFocus();
         //
       
        modTbProduto.setNumRows(0);
        
         
         
        
        
        
    }//GEN-LAST:event_brnAlterarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton brnAlterar;
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnConsultarCliente;
    private javax.swing.JButton btnConsultarItemPedido;
    private javax.swing.JButton btnConsultarPedido;
    private javax.swing.JButton btnConsultarVendedor;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnIncluir;
    private javax.swing.JButton btnRemoveItem;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnValidar;
    private javax.swing.ButtonGroup btngrFormaPagamento;
    private javax.swing.JFormattedTextField ftxtCPFCliente;
    private javax.swing.JFormattedTextField ftxtCPFVendedor;
    private javax.swing.JFormattedTextField ftxtDataPedido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanelDadosCliente;
    private javax.swing.JPanel jPanelDadosVendedor;
    private javax.swing.JPanel jPanelFormaPag;
    private javax.swing.JPanel jPanelItensPedido;
    private javax.swing.JPanel jPanelPedido;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblItemPedido;
    private javax.swing.JLabel lblNumPed;
    private javax.swing.JLabel lblQtdeItensPedido;
    private javax.swing.JLabel lblValorTotaltPed;
    private javax.swing.JLabel lblVendedor;
    private javax.swing.JRadioButton rbtnPrazo;
    private javax.swing.JRadioButton rbtnVista;
    private javax.swing.JTable tbProduto;
    private javax.swing.JTextField txtNumPed;
    private javax.swing.JTextField txtQtd;
    private javax.swing.JTextField txtcodProd;
    // End of variables declaration//GEN-END:variables
    private ArrayList<Pedido> pedido;
    private ArrayList<Pedido> pedido2;
    private ArrayList<Pessoa> clie_vend;
    private ArrayList<Produto> produto;
    private ArrayList<ItemPedido> itm_ped;
    private Produto prod;
    private Pedido ped;
    private ItemPedido iped;
    private Cliente cliente;
    private Vendedor vendedor;
    
    private int posPedido = 0;
     //Variavel pra armazenar Pessoa/Produto
    private int posPesClie, posProduto, quant=0, valor=0;
    private DefaultTableModel modTbProduto;
    private double total=0,subtotal;
    private int codItemPedido = 1 ;
    
}
